# baseURL: https://www.jamesbradbury.xyz
baseURL: /
languageCode: "en-us"
title: james bradbury
theme: book

publishDir: public

enableGitInfo: false
disableKinds: ['taxonomy', 'taxonomyTerm']
params:
  BookToC: false
  BookRepo: false
  BookSearch: false
  BookMenuBundle: /menu

markup:
  goldmark:
    renderer:
      unsafe: true
